[package]
name = "sphero-rs"
version = "0.1.0"
authors = ["Tim Boldt <tim.boldt@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.4.3"
global_counter = "0.2.2"
linux-embedded-hal = "0.3.2"
pwm-pca9685 = "0.3.1"
